name: Run PHP Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: PHP 8.0
    defaults:
      run:
        working-directory: ./php
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        tools: composer:v2
        coverage: none
    - name: Install PHP dependencies
      run: composer update --prefer-stable --no-interaction --no-progress --ansi
    - name: Run Unit Tests
      run: ./vendor/bin/pest --colors=always
